require 'cora'
require 'siri_objects'
require 'pp'

#######
# This is a French SiriProxy Plugin
# Remember to add the plugin to the "config.yml" !
######

class SiriProxy::Plugin::SiriSutra < SiriProxy::Plugin
  def initialize(config)
	#if you have custom configuration options, process them here!
  end

  listen_for /position|sutra|sex/i do

	imgs = [["Le sexy V","http://mathieubolard.com/sutra/das-erotische-v.jpg","Ce poste requiert des compétences acrobatiques! La femme s'assied au bord d'une table. Elle pose ensuite ses jambes sur les épaules de son partenaire. Ce dernier prend appui en tenant ses fesses."],
			["Le cheval à bascule","http://mathieubolard.com/sutra/das-fantastische-schaukelpf.jpg","L'homme est assis en tailleur. La femme est assise sur lui et tournée vers lui. L'homme peut s'appuyer contre un mur pour soulager ses bras et en profiter pour caresser sa partenaire."],
			["Entremêlé","http://mathieubolard.com/sutra/das-feuerrad.jpg","Cette position est plus compliquée qu'elle n'y paraît ! Dans un premier temps l'homme et la femme sont sur le côté. Ensuite, elle enroule ses jambes autour de son torse. Pour maintenir l'équilibre, il l'aide avec ses deux mains. Il entoure sa taille avec ses jambes, en se tenant à sa cuisse et se déplace doucement de haut en bas."],
			["Le triangle lumineux","http://mathieubolard.com/sutra/das-gluehende-dreieck.jpg","La femme s'allonge sur le dos et l'homme sur elle. L'astuce ? L'homme se met à quatre pattes. Puis la femme soulève son bassin dans la direction de son pénis qu'il peut pénétrer. L'homme reste dans cette position, tandis que la femme peut bouger son bassin de haut en bas. Ambiance garantie."],
			["Le grand X","http://mathieubolard.com/sutra/das-grosse-x.jpg","L'homme s'allonge sur le lit avec les jambes légèrement écartées. La femme s'assoit sur ​​lui et lui tourne la tête. Ensuite, elle étire ses jambes vers l'arrière dans le sens de ses épaules. La partie supérieure du corps est en avant vers les pieds de l'homme. Tout le monde est prêt ? La femme s'appuie sur les jambes de son partenaire et commence à donner le rythme."],
			["Le Nirvana","http://mathieubolard.com/sutra/das-nirvana.jpg","Madame s'allonge sur le dos, les jambes tendues et les bras au-dessus de sa tête. Monsieur s'allonge sur elle."],
			["Le cadenas","http://mathieubolard.com/sutra/das-vorhaengeschloss.jpg","La femme monte sur un meuble (plan de travail, machine à laver...). Le principal est qu'elle soit assise en tailleur sur le bord et en s'aidant de ses bras pour se tenir. Il se tient devant elle, puis elle enveloppe ses jambes étroitement autour de sa taille."],
			["Le gaufrier","http://mathieubolard.com/sutra/das-waffeleisen.jpg","Pour la position du gaufrier, l'homme s'allonge sur le dos, la femme sur lui avec les jambes légèrement écartées. Monsieur commence avec des mouvements doux. Notez que cette position est bien pour les femmes qui aiment garder le contrôle."],
			["Le singe","http://mathieubolard.com/sutra/der-affe.jpg","L'homme s'allonge sur le dos et tire ses genoux vers lui. Elle s'assied sur lui en lui tournant le dos. Madame a besoin de beaucoup de force pour la position du singe, elle peut donc s'aider en tenant les mains de son partenaire."],
			["Le papillon","http://mathieubolard.com/sutra/der-aufregende-schmetterlin.jpg","Allongez-vous sur une table madame. Posez vos jambes sur ​​les épaules de votre partenaire puis soulevez vos fesses afin qu'il les attrapent."],
			["L'union suspendue","http://mathieubolard.com/sutra/der-aufstieg-zur-lust.jpg","Monsieur est debout et soulève madame. Elle se tient en face de lui et enroule ses jambes autour de lui. Petite astuce ? Elle peut poser ses pieds sur le lit ou un canapé pour s'aider. Maintenant, il peut jouer en faisant un mouvement d'ascenseur du haut vers le bas."],
			["Le bouton de rose","http://mathieubolard.com/sutra/der-balanceakt.jpg","L'homme s'allonge sur le dos, les genoux pliés vers lui et écartés. La femme s'assied sur lui tandis qu'il la tient par la taille. Dans cette position, c'est l'homme qui donne le rythme de mouvement. La femme peut caresser le point de départ de la branche - une zone très érogène."],
			["La pieuvre","http://mathieubolard.com/sutra/der-beinstrecker.jpg","Madame est allongée et pose une jambe en position sur l'épaule de son partenaire. L'homme s'agenouille devant elle. L'homme a une main libre pour masser les seins."],
			["La cuillère","http://mathieubolard.com/sutra/der-besturzte-engel.jpg","L'homme et la femme sont couchés en position cuillère. Dans cette position, il peut caresser les seins. Position recommandée pour les femmes enceintes !"],
			["Le petit pont","http://mathieubolard.com/sutra/der-bruckenpfeiler.jpg","L'homme fait un pont. Elle s'assoit sur ​​lui et bouge ses hanches doucement d'avant en arrière. La taille du corps et le poids des deux partenaires doivent s'emboîter de manière à éviter les fractures et les crampes. Souplesse recommandée !"],
			["L'union du papillon","http://mathieubolard.com/sutra/der-clip.jpg","L'homme s'allonge sur le dos avec les jambes serrées. La femme s'assoit sur ​​lui et se penche son corps vers l'arrière pour se tenir avec ses mains. C'est la femme qui détermine le rythme des mouvements. Le petit plus ? L'homme peut ainsi caresser et stimuler le clitoris de sa partenaire."],
			["La position 99","http://mathieubolard.com/sutra/der-close-up.jpg","L'homme et la femme sont couchés sur le côté et monsieur s'accroche fermement à la femme par derrière. Elle le serre avec ses jambes. L'homme caresse le clitoris de la femme. Elle peut aussi stimuler le plaisir de monsieur en caressant son pénis."],
			["L'union du crabe","http://mathieubolard.com/sutra/der-doppeldecker.jpg","L'homme s'allonge sur le dos, la femme sur lui. Elle s'appuie sur ses coudes, les genoux pliés. L'homme qui tient la femme à la taille, pénètre sa partenaire avec des mouvements doux. La femme aide en remuant le bassin et les hanches. "],
			["La danse de séduction","http://mathieubolard.com/sutra/der-face-to-face-fandango.jpg","La femme s'allonge sur le dos et plie ses jambes. Les bras sont maintenus à raide au dessus de la tête. L'homme s'allonge sur sa partenaire avec les jambes droites, pour la pénétrer. Avec ses mains, il peut soutenir les épaules ou à la taille de la femme. Une fois qu'il a trouvé une position confortable pour les deux, l'acte peut commencer. Mouvements circulaires ou profonds, faites votre choix !"],
			["La balançoire","http://mathieubolard.com/sutra/der-faulenzer.jpg","L'homme est allongé et sa partenaire s'assied sur lui en lui tournant le dos. Madame mène la danse !"],
			["Le bateau ivre","http://mathieubolard.com/sutra/der-federnde-held.jpg","La femme s'allonge sur le dos, tire ses genoux vers sa poitrine et tend ses pieds vers le haut. L'homme à genoux la pénètre. Dans cette position, la femme peut caresser les testicules de son compagnon."],
			["Le flipper","http://mathieubolard.com/sutra/der-flipper.jpg","La femme fait un pont en gardant la tête allongée. L'homme vient s'emboîter. Cette position est considérée comme très sportive et difficilement supportable sur la durée. Vous pouvez donc passer dans une position plus confortable par la suite."],
			["La grenouille","http://mathieubolard.com/sutra/der-frosch.jpg","L'homme est assis sur le bord du lit, les pieds par terre. La femme est assise dos à lui sur le lit de telle manière que son pénis ne peut y pénétrer. Il guide sa partenaire en la soutenant avec ses mains sur ses cuisses. Notez qu'il peut aussi caresser ses seins et son clitoris."],
			["La victoire","http://mathieubolard.com/sutra/der-gluehende-wacholder.jpg","La femme s'allonge sur le dos avec les genoux pliés. L'homme se glisse entre ses genoux et soulève son bassin légèrement pour pouvoir y pénétrer. Il embrasse son ventre... Une position très romantique."],
			["La Grande Ourse","http://mathieubolard.com/sutra/der-grosse-wagen.jpg","La femme se trouve face vers le bas sur le lit. Elle se tient sur les coudes. L'homme vient entre soulève ses jambes pour la pénétrer."],
			["Le 69 gagnant","http://mathieubolard.com/sutra/der-klammergriff.jpg","L'homme s'allonge sur le côté. La femme est nichée à côté de lui, mais à l'envers. Sa tête est vers le bas et serrée dans ses cuisses ouvertes. Elle frotte ses seins contre le corps et les cuisses de son partenaire. L'homme peut, alors qu'il pénètre, mettre avec son doigt dans l'anus de sa compagne."],
			["La classique","http://mathieubolard.com/sutra/der-klassiker.jpg","Pour la position classique dite traditionnelle du Kamasutra, la femme s'allonge sur le dos avec les jambes écartées. L'homme s'allonge sur elle. Cette position est stimulante et relaxante en même temps, les partenaires peuvent s'embrasser et se regarder."],
			["L'union de l'éléphante","http://mathieubolard.com/sutra/der-kniefall.jpg","L'homme et la femme s'agenouillent en face l'un de l'autre. L'homme positionne sa jambe entre elle et pénètre sa partenaire. Dans cette position, de nombreuses caresses intimes sont possibles."],
			["La croix enflammée","http://mathieubolard.com/sutra/der-kreuzstich.jpg","La femme s'allonge sur le dos, une jambe tendue, l'autre repliée. L'homme est assis à califourchon sur ses cuisses tendues. Il se tient avec une main sur la cuisse de sa partenaire."],
			["Le fauteuil inclinable","http://mathieubolard.com/sutra/der-liegestuhl.jpg","L'homme s'assied et s'appuie sur ses mains. La femme se trouve confortablement sur ​​un coussin, tandis que ses jambes sont sur les épaules de l'homme. Il se déplace ensuite d'avant en arrière."],
			["La position du Lotus","http://mathieubolard.com/sutra/der-lotus-sitz.jpg","La femme s'allonge sur le dos et replie ses jambes tandis que l'homme se trouve entre ses cuisses et pénètre par le haut. Ainsi, la femme ne doit pas supporter son poids, il est recommandé qu'il soit pris en charge sur les bras. Encore plus de plaisir peut faire cette position quand l'homme met un oreiller sous ses fesses pour changer l'angle de pénétration. Un autre avantage de cette position: ils ont les mains libres pour profiter soit de ses propres zones érogènes."],
			["La liane","http://mathieubolard.com/sutra/der-luesterne-beinstrecker.jpg","La femme et l'homme sont face à face. Madame pose une jambe sur l'épaule de son partenaire et le tient par le cou."],
			["Le président vigoureux","http://mathieubolard.com/sutra/der-lustvolle-lehnstuhl.jpg","La femme est debout sur le lit ou sur une chaise, l'homme est derrière elle, de sorte que sa poitrine a touché son dos. Madame plie ses genoux et monsieur la rattrape par les fesses."],
			["La montagne magique","http://mathieubolard.com/sutra/der-magische-berg.jpg","Tout d'abord, mettez un tas d'oreillers sur le sol. Sur cette montagne, la femme peut s'appuyer le haut du corps tandis que son partenaire se cramponne à elle."],
			["Les munitions","http://mathieubolard.com/sutra/der-patronengurt.jpg","La femme s'allonge sur le dos et tire vers le haut ses jambes, l'homme se met à genoux et la pénètre. Dans cette position, le point G est stimulé plus intensément. L'homme doit presser les genoux de sa partenaire dans le but d'augmenter la puissance du plaisir."],
			["L'hélice de l'amour","http://mathieubolard.com/sutra/der-propeller-der-leidensch.jpg","Super show à 360 degrés ! Dans ce numéro, l'homme s'allonge dos et sur la femme."],
			["La charette","http://mathieubolard.com/sutra/der-rocjnroller.jpg","Madame se couche sur le dos et les jambes tendues. Monsieur s'agenouille devant elle et écarte ses jambes, pour mettre sa tête entre tout en tenant ses hanches. Elle s'accroche à lui pour profiter du mouvement de balancement. Les partenaires ont un contact avec les yeux et peuvent utiliser les deux mains pour caresser."],
			["L'acte de retour","http://mathieubolard.com/sutra/der-rueckenakt.jpg","Dos à son partenaire, la femme s'appuie contre un fauteuil rembourré ou une chaise. L'homme est pressé contre elle par derrière et peut déplacer sa main entre ses jambes légèrement écartées voire même lui caresser le clitoris."],
			["Le noeud coulant","http://mathieubolard.com/sutra/der-schaukelstihl.jpg","L'homme s'allonge sur le dos. La femme s'assied sur lui. Aider par la femme, monsieur se relève tandis qui'elle enroule ses jambes autour de sa taille et vice-versa. Les deux partenaires sont face à face et peuvent s'accrocher les coudes, et s'embrasser."],
			["Le papillon","http://mathieubolard.com/sutra/der-schmetterling.jpg","La femme s'agenouille sur le lit avec les jambes grandes ouvertes devant son partenaire. Il lève les jambes légèrement et les maintient au niveau des chevilles ou des cuisses. Cette position est très excitante pour les deux partenaires."],
			["L'équilibriste","http://mathieubolard.com/sutra/der-spannungsbogen.jpg","L'homme debout soulève sa partenaire perpendiculairement à lui tandis qu'elle se tient d'une main au sol. Inconvénient mineur de cette position acrobatique : l'homme doit être fort, mais le jeu en vaut la chandelle !"],
			["L'étoile","http://mathieubolard.com/sutra/der-stern.jpg","La femme s'allonge sur le dos, une jambe pliée, l'autre à plat. L'homme s'assied entre ses jambes en poussant une jambe sous ses fesses et se repose avec ses mains."],
			["La levrette","http://mathieubolard.com/sutra/der-super-g.jpg","Madame à quatre pattes et monsieur agenouillé derrière, voilà comment se déroule la levrette. C'est une des positions favorites du Kamasutra. Conseil ? Évitez les endroits au sol dur, sinon vous pourriez avoir mal au genoux après !"],
			["L'arc de triomphe","http://mathieubolard.com/sutra/der-triumphbogen.jpg","L'homme est assis avec les jambes tendues sur le lit. La femme s'assied sur ses genoux face à lui. Après avoir trouvé une position confortable, elle se penche en arrière entre les jambes de l'homme. Ensuite l'homme se penche en avant et le plaisir commence."],
			["Le cavalier perdu","http://mathieubolard.com/sutra/der-verirrte-reiter.jpg","L'homme s'allonge sur le dos. Elle s'assied dos à lui et se déplace d'avant en arrière. Dans cette position, la femme peut se caresser elle-même le clitoris."],
			["Le point de 8","http://mathieubolard.com/sutra/die-8er-nummer.jpg","La femme est allongée sur le dos, éventuellement avec un oreiller sous ses fesses. Lui est dessus les bras tendus. Le chiffre 8, symbole de l'infini... et de paresse."],
			["L'amazone","http://mathieubolard.com/sutra/die-amazone.jpg","L'homme est assis confortablement sur une chaise, la femme s'assied sur lui. Comme elle se déplace d'avant en arrière, il peut lui caresser ses seins. Une position très stimulante."],
			["Le culte","http://mathieubolard.com/sutra/die-anbetung.jpg","La femme est à quatre pattes et se tient sur ses avant-bras. lui est derrière. La pénétration profonde stimule la zone intérieure du vagin et du point G chez les femmes. L'homme peut aussi caresser ses seins et le clitoris de leur partenaire."],
			["Le canapé lit","http://mathieubolard.com/sutra/die-bettkarriere-fuers-sofa.jpg","La femme est allongée et monsieur debout tient les jambes de sa partenaire. Puis elle ouvre et ferme ses jambes pour donner le rythme."],
			["Le voyage en bateau","http://mathieubolard.com/sutra/die-bootsfahrt.jpg","L'homme s'allonge sur le dos. La femme s'assied sur lui de coté. La femme donne le rythme."],
			["A l'envers","http://mathieubolard.com/sutra/die-elektrisierende-rutsche.jpg","La femme est couchée à plat ventre sur le lit. Ses jambes sont légèrement écartées. L'homme s'assied sur la femme par derrière, les jambes sont idéalement placés à côté du haut de son corps. Avec ses bras, il se penche vers l'arrière et se déplace facilement d'avant en arrière. Petit plus ? Pour une sensation encore plus de folie, la femme ferme légèrement les jambes."],
			["Le foetus","http://mathieubolard.com/sutra/die-embryonalstellung.jpg","Madame s'allonge sur le dos, tire ses jambes vers sa poitrine et les met sur ​​les épaules de son partenaire, qui se penche sur elle. Dans cette position, le pénis pénètre très profondément et vous devez donc veiller à ce que le vagin soit bien humidifié. Cette position peut être très excitante pour la femme, surtout si elle continue quand l'homme à éjaculer."],
			["Le transat","http://mathieubolard.com/sutra/die-faulenzerin.jpg","L'homme s'agenouille devant la femme allongée, et s'appuie lui-même avec ses bras par derrière. La femme est couchée avec jambes repliées sur le lit, la tête appuyée sur un oreiller. Ils ont placé la jambe ouverte de sorte que le pénis peut y pénétrer de manière optimale. Particulièrement stimulant: les deux partenaires peuvent se voir."],
			["Le piège","http://mathieubolard.com/sutra/die-fussangel.jpg","L'homme est à genoux avec une jambe légèrement inclinée sur le côté. La femme se repose sur ses avant-bras, attrape le pénis de son partenaire et donne le rythme de la pénétration. Avec sa main libre l'homme peut caresser les seins ou les fesses. Il est conseillé de faire cette position sur un tapis, mais pas nécessairement dans le lit."],
			["La force G","http://mathieubolard.com/sutra/die-g-macht.jpg","Elle s'allonge sur le dos et tire ses genoux près de sa poitrine. Il s'agenouille devant elle et lui tenant les pieds, puis il entre en elle. C'est lui qui donne le rythme et la profondeur de pénétration."],
			["Le numéro de la maison","http://mathieubolard.com/sutra/die-hausnummer.jpg","Elle s'allonge sur le dos avec un oreiller sous les fesses. Lui se met à genoux entre ses jambes. Cette position lui permet une pénétration très profonde. Elle croise ses jambes autour de lui."],
			["Le défi","http://mathieubolard.com/sutra/die-herausforderung.jpg","La femme est debout sur une chaise, son corps penché en avant et les coudes sur les genoux. Monsieur derrière détermine le rythme des mouvements avant et arrière. Ceux qui acceptent le défi, gagnent une plaisir optimal."],
			["Le dévouement","http://mathieubolard.com/sutra/die-hingabe.jpg","La femme est allongée et l'homme se glisse entre ses jambes écartées et soulève son bassin. Il se penche en avant avec sa bouche et caresse son ventre. Il détermine le rythme du mouvement, tandis que la femme se donne à lui complètement détendue."],
			["La réunion chauffée","http://mathieubolard.com/sutra/die-hitzige-sitzung.jpg","L'homme assis sur une chaise, la femme est assise sur ses genoux."],
			["La bougie","http://mathieubolard.com/sutra/die-kerze.jpg","La femme repose à plat sur ​​son dos, les jambes en l'air. L'homme s'agenouille devant la femme. Pour plus d'appui , madame peut peut se tenir aux cuisses de son partenaire."],
			["La position de base","http://mathieubolard.com/sutra/die-klammer-stellung.jpg","L'homme s'allonge les jambes écartées, la femme est sur lui, les cuisses serrées. Elle frotte ainsi ses seins contre le corps de son partenaire."],
			["Le bretzel amoureux","http://mathieubolard.com/sutra/die-leidenschaftliche-breze.jpg","Les deux partenaires s'agenouillent l'un en face de l'autre. Puis ils placent une jambe à la gauche de l'autre. Les deux se déplacent ensuite doucement d'avant en arrière."],
			["La brouette","http://mathieubolard.com/sutra/die-leidenschaftliche-schub.jpg","La femme se repose sur ses avant-bras et lève les jambes que son partenaire, agenouillé derrière, rattrape. Cette position est fatigante donc temporaire... Pensez à la suite !"],
			["La fleur de lotus","http://mathieubolard.com/sutra/die-lotusblume.jpg","L'homme est assis les jambes croisées sur le lit, la femme est assise sur ses genoux. Monsieur donne le rythme."],
			["La sirène","http://mathieubolard.com/sutra/die-meerjungfrau.jpg","Elle s'allonge sur le dos sur le bord d'un lit, d'une table ou d'un comptoir. Un oreiller sous les fesses peut donner une impulsion. Elle glisse ses mains sous les fesses ou le coussin. Vous pouvez aussi tout simplement laisser les mains en vrac. Monsieur se tient devant elle et attrape ses pieds."],
			["Le L","http://mathieubolard.com/sutra/die-popoese-aussicht.jpg","Dans cette position du Kamasutra l'homme est assis, les jambes allongées sur le lit, le sol ou n'importe où ailleurs. La femme est à plat ventre et lui tourne le dos. Les jambes sont tirées en arrière. Ensuite, elle se déplace lentement vers le haut et vers le bas. Elle utilise les pieds de l'homme pour se stabiliser et glisser."],
			["La cuisine portugaise","http://mathieubolard.com/sutra/die-portugiesische-galeere.jpg","L'homme étend ses jambes en position assise. La femme se met à quatre pattes dos à lui. C'est lui qui détermine le rythme du mouvement. L'homme peut caresser les seins de sa main libre, et les fesses."],
			["L'antilope","http://mathieubolard.com/sutra/die-rossantilope.jpg","L'homme soulève sa compagne. L'avantage ? Cette position de départ permet aux partenaires une pénétration plus profonde. L'inconvénient ? Ne convient que pour les poids plumes et les hommes forts !"],
			["La balle gagnante","http://mathieubolard.com/sutra/die-ruhige-kugel.jpg","L'homme est assis avec les jambes légèrement fléchies au sol. La femme s'assoit dos à son partenaire sur ses genoux. Elle se penche vers l'avant, et son partenaire la suit. Cette position requiert un certain degré de souplesse pour les deux partenaires."],
			["La semie-brouette","http://mathieubolard.com/sutra/die-schubkarre.jpg","La femme est à quatre pattes. L'homme s'agenouille derrière elle et lui tient une seule jambe. Cette position est une position temporaire car elle est fastidieuse à long terme pour le partenaire de sexe féminin."],
			["Le latéral","http://mathieubolard.com/sutra/die-seitliche-samba.jpg","La femme s'allonge sur le lit sur le côté dans la position L (jambes tendues en angle droit). Lui est derrière elle dans une sorte de position cuillère."],
			["La paire de ciseaux","http://mathieubolard.com/sutra/die-sexy-schere.jpg","Monsieur s'allonge sur le dos les genoux vers lui et les jambes en l'air. Sa partenaire s'assied sur lui et tous deux se tiennent les mains."],
			["Le Sphinx","http://mathieubolard.com/sutra/die-sphinx.jpg","La femme s'allonge sur ses avant-bras et replie une jambe. L'homme se penche sur elle et se tient sur ses bras."],
			["Le loup","http://mathieubolard.com/sutra/die-standhafte.jpg","L'homme et la femme sont debout. Madame lui tourne le dos. Il tient ses mains, les bras tendus. La femme peut s'appuyer sur une table garder l'équilibre."],
			["Le cocktail","http://mathieubolard.com/sutra/die-stehparty.jpg","Debout, l'homme frotte son pénis contre sa partenaire. Si l’excitation monte, il peut la pénétrer. Cependant, il ne peut pas y avoir une pénétration profonde avec cette position qui nécessite souvent que la femme soit sur ses orteils ou porte des talons hauts."],
			["La reine fière","http://mathieubolard.com/sutra/die-stolze-koenigin.jpg","L'homme est couché. La femme est assise à califourchon sur lui et lui tourne le dos. Il pose ses mains sur ses fesses pour la guider. La femme peut augmenter l'excitation de l'homme, en lui caressant ses testicules."],
			["Le contorsionniste","http://mathieubolard.com/sutra/die-supernova.jpg","L'homme est allongé sur le lit avec la tête vers le bas. La femme s'assied sur ​​lui."],
			["La tarentule","http://mathieubolard.com/sutra/die-tarantel.jpg","L'homme s'appuie sur ses mains, les jambes sont tendues. La femme s'assied face à lui."],
			["L'affaire escalier","http://mathieubolard.com/sutra/die-treppenaffare.jpg","Madame s'agenouille sur un escalier, l'homme est derrière elle. Si les deux partenaires se sentent, ils peuvent monter l'escalier pendant l'acte sexuel."],
			["La déesse","http://mathieubolard.com/sutra/die-wippe.jpg","L'homme est assis sur le sol ou sur un lit pas trop mou, une jambe est étendue, tandis que l'autre est légèrement plié pour maintenir l'équilibre. La femme s'assoit sur ​​lui."],
			["Le Y","http://mathieubolard.com/sutra/die-y-kurve.jpg","La femme se trouve face vers le bas du lit et les coudes au sol. L'homme s'allonge sur les jambes de sa partenaire entre les siennes. Cela forme un 'Y'."],
			["La paire de ciseaux","http://mathieubolard.com/sutra/die-zange.jpg","Pour cette position, les femmes ayant de la force dans les bras est un avantage évident. L'homme soulève la taille de sa partenaire, qui l'escalade avec sa jambe gauche, levant sa jambe droite. Maintenant, il la pénètre alors qu'elle est suspendue. Le sang de la femme circule plus vite dans ce sens... orgasme explosif garanti!"],
			["L'union de l'aigle","http://mathieubolard.com/sutra/die-zen-pause.jpg","Ce position offre un moment de détente aux deux partenaires. Les deux se trouvent sur le côté, afin qu'ils se regardent. Madame pose sa jambe sur les hanches de l'homme."],
			["Face à face","http://mathieubolard.com/sutra/face-to-face.jpg","L'homme et la femme sont couchés sur le côté, l'un en face de l'autre. Elle l'enroule avec ses jambes."],
			["Entrecroisé","http://mathieubolard.com/sutra/hin-und-her.jpg","L'homme s'allonge sur le dos avec les jambes légèrement écartées. Elle s'assoit sur ​​lui et se repose ses bras en arrière."],
			["En l'air","http://mathieubolard.com/sutra/hoch-hinaus.jpg","La femme s'allonge sur le dos. Elle s'étend ses jambes en l'air. L'homme s'agenouille devant elle et pousse ses jambes sur le côté."],
			["L'angle droit","http://mathieubolard.com/sutra/im-rechten-winkel.jpg","La femme s'allonge sur le dos et l'homme en face d'elle peut ainsi lui caresser la poitrine. Cette position peut être effectuée sur une table."],
			["Position de l'Indra","http://mathieubolard.com/sutra/indrani.jpg","Elle s'allonge sur le dos, genoux pliés et tirés vers le haut de sa poitrine. Il s'agenouille devant elle avec ses mains sur ses fesses. Les jambes de madame passent sous les aisselles de son partenaire."],
			["La bougie enflammée","http://mathieubolard.com/sutra/kerze.jpg","La femme repose sur sa tête et ses épaules tandis que son partenaire lui tient les jambes en l'air. Pour plus d'appui il peut tenir les cuisses de sa partenaire."],
			["Une chaise pour 2","http://mathieubolard.com/sutra/limbo-liebe.jpg","L'homme est tranquillement assis sur une chaise. Sa partenaire est à califourchon sur ses genoux, puis elle lève son jambes pliées et les met sur ses épaules. Il la tient par les hanches."],
			["Le cheval infernal","http://mathieubolard.com/sutra/master.jpg","L'homme s'allonge sur le dos, les deux jambes sont pliées. Assise sur lui, elle lui tourne le dos."],
			["Dos au mur","http://mathieubolard.com/sutra/mit-dem-ruecken-zur-wand.jpg","Les deux partenaires sont debout, madame tourne le dos à son compagnon..."],
			["L'aigle","http://mathieubolard.com/sutra/nummer-sicher.jpg","La femme s'allonge sur le dos et écarte les jambes. L'homme s'allonge sur elle et la pénètre. Ils ont les mains libres et peuvent se caresser... hummm !"],
			["Masse-moi !","http://mathieubolard.com/sutra/seitlich.jpg","La femme est allongée à plat ventre. Son partenaire enfourche une de ses jambes. Il tend une jambe tandis que l'autre est pliée."],
			["La fourchette","http://mathieubolard.com/sutra/sinnliches-hin-und-her.jpg","L'homme et la femme sont allongés perpendiculairement. Leurs jambes s'entremêlent..."],
			["A l'envers","http://mathieubolard.com/sutra/upside-down.jpg","L'homme est assis sur une chaise. Madame, sur lui, se penche en s'accrochant avec ses bras autour de lui à l'arrière. L'homme pénètre sa partenaire et caressant sa poitrine ici. Cette position requiert beaucoup d'agilité."],
			["La chaise à porteur","http://mathieubolard.com/sutra/vulkanfieber.jpg","Un peu comme la position de la brouette, l'homme attrape sa partenaire par les hanches."],
			["L'huitre","http://mathieubolard.com/sutra/wackelpeter.jpg","La femme est allongée, les genoux pliés. L'homme s'agenouille devant elle et décale ses jambes sur le côté."],
			["La trêve","http://mathieubolard.com/sutra/waffenstillstand.jpg","Il est allongé sur le côté perpendiculaire à sa partenaire, elle aussi couchée mais sur le dos. Gare aux mains libres dans cette position !"],
			["Le câlin amélioré","http://mathieubolard.com/sutra/weit-geoeffnet.jpg","L'homme est à genoux sur le lit, elle s'allonge sur le dos devant lui, en levant les fesses et enveloppe ses jambes autour de lui."],
			]
	
	r = Random.rand(imgs.length)
	say imgs[r][2], spoken: imgs[r][0]
	push_image(imgs[r][0], imgs[r][1])
	request_completed #always complete your request! Otherwise the phone will "spin" at the user!
  end
  
  def push_image(title, image)
	object = SiriAddViews.new
	object.make_root(last_ref_id)
	answer = SiriAnswer.new(title, [SiriAnswerLine.new('logo', image)])
	object.views << SiriAnswerSnippet.new([answer])
	send_object object
  end
    
end
